fix mdsal version to match controller (and its impacts)
When I originally wrote this code we were in the beginning of Neon; at
that time, controller was still dependent on an mdsal SNAPSHOT.  Later
during Neon we moved to a fixed mdsal version - which this change does.

This fixes the following error in
org.opendaylight.etcd.testutils.test.EtcdDBTest :

java.lang.NoSuchMethodError:
org.opendaylight.yangtools.yang.binding.CodeHelpers.wrapperHashCode(Ljava/lang/Object;)I
	at org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.controller.md.sal.test.list.rev140701.two.level.list.TopLevelListKey.hashCode(TopLevelListKey.java:38)